FROM librecat_base
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
# Finalizing the LibreCat Image with SUB Layer
#

RUN git clone https://github.com/subugoe/goefis.git
WORKDIR /srv/LibreCat/goefis
RUN npm install \
    && npm run build-css prefix-css

# Clean up
RUN apt-get clean \
    && apt purge -y binutils \
    wget \
    git \
    pwgen \
    binutils \
    build-essential \
    nodejs \
    g++ \
    man-db \
    perl-doc \
   && apt-get --purge -y autoremove \
   && rm -rf /var/lib/apt/lists/*

WORKDIR ${LIBRECATHOME}
COPY conf/layers.yml .
COPY docker-entrypoint.sh .
COPY gearman-entrypoint.sh gearboot.sh
RUN chown -R librecat:librecat ${LIBRECATHOME}

USER librecat:librecat

VOLUME ["/usr/share/elasticsearch/data","/var/lib/mysql", "/srv/LibreCat/logs"]

EXPOSE 2022 3306 4730 5001 9200 9300

ENTRYPOINT ["./docker-entrypoint.sh"]
