FROM librecat_base
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
# Finalizing the LibreCat Image with SUB Layer
#
# Local Layer
ENV LOCAL_LAYER /opt/local
ENV SETTINGS_LAYER /opt/settings
RUN git clone https://github.com/subugoe/goefis.git ${LOCAL_LAYER}
WORKDIR ${LOCAL_LAYER}
RUN npm install \
    && npm run build-css prefix-css

RUN mkdir -p ${SETTINGS_LAYER}
COPY settings ${SETTINGS_LAYER}

# Configurations
WORKDIR ${LIBRECATHOME}
COPY layers.yml .
COPY boot.sh .
COPY gearman-entrypoint.sh .
COPY docker-entrypoint.sh .

RUN chown -R librecat:librecat ${LIBRECATHOME} ${LOCAL_LAYER} ${SETTINGS_LAYER}

# Clean up
# As a result the created image would be much smaller. It's our recommendation to
# uncomment the few lines below in a production environment.
#RUN apt-get clean \
#    && apt purge -y ${PRE_BUILD} \
#    perl-doc \
#    nodejs
#    && apt-get --purge -y autoremove \
#    && rm -rf /var/lib/apt/lists/*

USER librecat:librecat

VOLUME ["/usr/share/elasticsearch/data","/var/lib/mysql", "/srv/LibreCat/logs"]

EXPOSE 3360 4730 5001 9200 9300

ENTRYPOINT ["./docker-entrypoint.sh"]
