FROM ubuntu:16.04
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
# creating a predecessor for the LibreCat Image
#

# Add extra Repository for ElasticSearch
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 \
    && echo "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" > /etc/apt/sources.list.d/elasticsearch-1.7.list
RUN sed -i '/multiverse/s/#[\ ]*deb/deb/g' /etc/apt/sources.list
RUN groupadd -g 5000 librecat \
    && useradd -g 5000 -u 5000 -d /srv/LibreCat -s /bin/bash -c "LibreCat User" librecat

ENV LIBRECATHOME /srv/LibreCat
ENV MYSQL_USER root
ENV NODEJS_URL https://deb.nodesource.com/setup_6.x
ENV PERL5LIB ${LIBRECATHOME}/local/lib/perl5:${LIBRECATHOME}/lib
ENV PRE_BUILD build-essential \
    ca-certificates \
    wget \
    g++ \
    numactl \
    xz-utils \
    bsdmainutils \
    git \
    man-db \
    imagemagick \
    libexpat1-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libgdbm-dev \
    libyaz-dev \
    libwrap0-dev \
    zlib1g \
    zlib1g-dev \
    binutils \
    pwgen \
    libaio1 \
    curl \
    telnet \
    sudo

# Prepare to install
# OS
RUN apt-get clean \
    && apt update \
    && apt upgrade -y \
    && apt dist-upgrade -y \
    && apt install -y ${PRE_BUILD}
# Perl
RUN apt install -y perl-doc \
    cpanminus \
    libcapture-tiny-perl \
    libdbd-mysql-perl \
    libmodule-install-perl \
    libyaml-perl \
    libb-utils-perl \
    carton
# Workers' Manager
RUN apt install -y gearman \
    gearman-server \
    gearman-tools \
    libgearman-dev
# MySQL
RUN apt install -y mysql-client \
    libmysqlclient-dev
# NodeJS
RUN curl -sL ${NODEJS_URL} | sudo -E bash - \
    && apt install -y nodejs

# Clone LibreCat
RUN mkdir -p ${LIBRECATHOME} \
     && git clone https://github.com/LibreCat/LibreCat.git ${LIBRECATHOME}

#   Installing Perl-Modules and compiling everything
#   Finalizing setup and run Web-Interface under :5001
#
# Building LibreCat
WORKDIR ${LIBRECATHOME}
# Goettingen specific: start ########
RUN git checkout 0.01_felix
# Goettingen specific: end ########
RUN sed -i 's/==/\>=/g' cpanfile 
RUN echo "requires 'Devel::Camelcadedb';" >> cpanfile
RUN carton install
RUN chmod +x bin/generate_forms.pl \
    && perl bin/generate_forms.pl

#Install perl debug module: https://github.com/Camelcade/Perl5-IDEA/wiki
#The module is now also added to the cpan file to place the dependency into the local directory by carton
RUN cpanm install Devel::Camelcadedb

# 
# Finalizing the LibreCat Image with SUB Layer
#
# Local Layer
ENV LOCAL_LAYER /opt/local
ENV SETTINGS_LAYER /opt/settings
RUN git clone https://github.com/subugoe/goefis.git ${LOCAL_LAYER}
WORKDIR ${LOCAL_LAYER}
RUN npm install \
    && npm run build-css prefix-css

RUN mkdir -p ${SETTINGS_LAYER}
COPY settings ${SETTINGS_LAYER}

# Configurations
WORKDIR ${LIBRECATHOME}
COPY layers.yml .
COPY boot.sh .
COPY gearman-entrypoint.sh .
COPY docker-entrypoint.sh .

RUN chown -R librecat:librecat ${LIBRECATHOME} ${LOCAL_LAYER} ${SETTINGS_LAYER}

# Clean up
RUN apt-get clean \
    && apt purge -y ${PRE_BUILD} \
    perl-doc \
    nodejs
    && apt-get --purge -y autoremove \
    && rm -rf /var/lib/apt/lists/*

USER librecat:librecat

VOLUME ["/usr/share/elasticsearch/data","/var/lib/mysql", "/srv/LibreCat/logs"]

EXPOSE 3306 4730 5001 9200 9300

ENTRYPOINT ["./docker-entrypoint.sh"]
