FROM ubuntu:16.04
MAINTAINER Arash Samadi (samadi@sub.uni-goettingen.de)
MAINTAINER Christian Mahnke (mahnke@sub.uni-goettingen.de)
# 
# creating a predecessor for the LibreCat Image
#

# Add extra Repository for ElasticSearch
#    && echo "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" > /etc/apt/sources.list.d/elasticsearch-1.7.list
RUN sed -i '/multiverse/s/#[\ ]*deb/deb/g' /etc/apt/sources.list
RUN groupadd -g 5000 librecat \
    && useradd -g 5000 -u 5000 -d /srv/LibreCat -s /bin/bash -c "LibreCat User" librecat

ENV LIBRECATHOME /srv/LibreCat
# Sets the version of LibreCat to check out
ARG LIBRECAT_VERSION=0.3.2
ENV MYSQL_USER root
ENV NODEJS_URL https://deb.nodesource.com/setup_6.x
ENV PERL5LIB ${LIBRECATHOME}/local/lib/perl5:${LIBRECATHOME}/lib
# Maybe this can speed up carton (Doesn't really help: https://github.com/perl-carton/carton/issues/203)
# ENV PERL_CPANM_OPT ”–skip-installed –notest –auto-cleanup=0″

ENV REQ_BUILD sudo \
    zlib1g \
    libaio1 
ENV PRE_BUILD build-essential \
    ca-certificates \
    wget \
    g++ \
    numactl \
    xz-utils \
    bsdmainutils \
    git \
    man-db \
    imagemagick \
    libexpat1-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libgdbm-dev \
    libyaz-dev \
    libwrap0-dev \
    zlib1g-dev \
    binutils \
    pwgen \
    curl \
    telnet \
    python \
    unzip

# Prepare to install
# OS
RUN apt clean \
    && apt update \
    && apt upgrade -y \
    && apt dist-upgrade -y \
    && apt install --assume-yes --no-install-recommends ${PRE_BUILD} ${REQ_BUILD}
# Perl
RUN apt install --assume-yes --no-install-recommends cpanminus \
    libcapture-tiny-perl \
    libdbd-mysql-perl \
    libmodule-install-perl \
    libyaml-perl \
    libb-utils-perl \
    carton
# Workers' Manager
RUN apt install --assume-yes --no-install-recommends gearman \
    gearman-server \
    gearman-tools \
    libgearman-dev
# MySQL
RUN apt install --assume-yes --no-install-recommends mysql-client \
    libmysqlclient-dev

# NodeJS
#RUN curl -sL ${NODEJS_URL} | sudo -E bash - \
RUN curl -sL ${NODEJS_URL} > /tmp/nodejs_preinstall \
    && sed -i 's/apt\-get/apt/g' /tmp/nodejs_preinstall \
    && sed -i 's/apt\ install\ -y/apt\ install\ \-\-assume\-yes\ \-\-no\-install\-recommends/g' /tmp/nodejs_preinstall \
    && chmod +x /tmp/nodejs_preinstall \
    && bash - /tmp/nodejs_preinstall \
    && apt install --assume-yes --no-install-recommends nodejs \
    && rm /tmp/nodejs_preinstall

# Clone LibreCat
RUN mkdir -p ${LIBRECATHOME} \
     && git clone https://github.com/LibreCat/LibreCat.git ${LIBRECATHOME}

#   Installing Perl-Modules and compiling everything
#   Finalizing setup and run Web-Interface under :5001
#
# Building LibreCat
WORKDIR ${LIBRECATHOME}
RUN git checkout ${LIBRECAT_VERSION} &&  sed -i 's/==/\>=/g' cpanfile && \
    echo "requires 'Devel::Camelcadedb';" >> cpanfile

RUN carton install
RUN perl bin/librecat generate forms

# See https://github.com/LibreCat/LibreCat/wiki/Installation#mathjax
# See https://github.com/LibreCat/LibreCat/wiki/Installation#markdown
RUN wget https://github.com/mathjax/MathJax/archive/v2.6-latest.zip && \
    cd public/javascripts && \
    unzip ../../v2.6-latest.zip && \
    mv MathJax-2.6-latest MathJax && \
    cd ../.. && \
    rm v2.6-latest.zip && \
    mkdir -p public/javascripts/commonmarkjs/dist/ && \
    cd public/javascripts/commonmarkjs/dist/ && \
    wget --no-check-certificate https://raw.githubusercontent.com/jgm/commonmark.js/master/dist/commonmark.min.js

ENTRYPOINT ["./docker-entrypoint.sh"]
