FROM ubuntu:14.04
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
# creating a predecessor for the LibreCat Image
#

# Add extra Repository for ElasticSearch
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 \
    && echo "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" > /etc/apt/sources.list.d/elasticsearch-1.7.list
RUN sed -i '/multiverse/s/#[\ ]*deb/deb/g' /etc/apt/sources.list
RUN groupadd -g 5000 librecat \
    && useradd -g 5000 -u 5000 -d /srv/LibreCat -s /bin/bash -c "LibreCat User" librecat

ENV LIBRECATHOME /srv/LibreCat
ENV MYSQL_USER root
ENV NODEJS_URL https://deb.nodesource.com/setup_6.x
ENV PERL5LIB ${LIBRECATHOME}/local/lib/perl5:${LIBRECATHOME}/lib

# Prepare to install
# OS
RUN apt-get clean \
    && apt update \
    && apt upgrade -y \
    && apt dist-upgrade -y \
    && apt install -y build-essential \
    ca-certificates \
    wget \
    g++ \
    numactl \
    xz-utils \
    bsdmainutils \
    git \
    man-db \
    ImageMagick \
    libexpat1-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libgdbm-dev \
    libyaz-dev \
    libwrap0-dev \
    zlib1g \
    zlib1g-dev \
    binutils \
    pwgen \
    libaio1 \
    curl
# Perl
RUN apt install -y perl-doc \
    cpanminus \
    libcapture-tiny-perl \
    libdbd-mysql-perl \
    libmodule-install-perl \
    libyaml-perl \
    libb-utils-perl \
    carton
# Workers' Manager
RUN apt install -y gearman \
    gearman-server \
    gearman-tools \
    libgearman-dev
# MySQL
RUN apt install -y mysql-client \
    libmysqlclient-dev
# NodeJS
RUN curl -sL ${NODEJS_URL} | sudo -E bash - \
    && apt install -y nodejs

RUN sed -i '/socket/ d' /etc/mysql/my.cnf \
    && sed -i '/\[mysqld\]/a bind-address\ =\ 0.0.0.0' /etc/mysql/my.cnf

# Clone LibreCat
RUN mkdir -p ${LIBRECATHOME} \
     && git clone --recursive https://github.com/LibreCat/LibreCat.git ${LIBRECATHOME}

#   Installing Perl-Modules and compiling everything
#   Finalizing setup and run Web-Interface under :5001
#
ENV LANG en_US.UTF-8
ENV LANGUAGE en.UTF-8
ENV LC_COLLATE en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_PAPER en_US.UTF-8
ENV LC_ADDRESS en_US.UTF-8
ENV LC_MONETARY en_US.UTF-8
ENV LC_NUMERIC en_US.UTF-8
ENV LC_TELEPHONE en_US.UTF-8
ENV LC_IDENTIFICATION en_US.UTF-8
ENV LC_MEASUREMENT en_US.UTF-8
ENV LC_TIME en_US.UTF-8
ENV LC_NAME en_US.UTF-8
RUN locale-gen en_US.UTF-8

WORKDIR ${LIBRECATHOME}
# Building LibreCat
RUN sed -i 's/==/\>=/g' cpanfile 
RUN carton install
RUN chmod +x bin/generate_forms.pl \
    && perl bin/generate_forms.pl

ENTRYPOINT ["./docker-entrypoint.sh"]
