FROM ubuntu:16.04
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
# creating a predecessor for the LibreCat Image
#

# Add extra Repository for ElasticSearch
RUN sed -i '/multiverse/s/#[\ ]*deb/deb/g' /etc/apt/sources.list
RUN groupadd -g 5000 librecat \
    && useradd -g 5000 -u 5000 -d /srv/LibreCat -s /bin/bash -c "LibreCat User" librecat

ENV LIBRECATHOME /srv/LibreCat
ARG LIBRECAT_VERSION=0.04
ENV LOCAL_LAYER /opt/local
ENV SETTINGS_LAYER /opt/settings
ENV MYSQL_USER root
ENV NODEJS_URL https://deb.nodesource.com/setup_6.x
ENV PERL5LIB ${LIBRECATHOME}/local/lib/perl5:${LIBRECATHOME}/lib
ENV REQ_BUILD sudo \
    zlib1g \
    libaio1 
ENV PRE_BUILD build-essential \
    ca-certificates \
    wget \
    g++ \
    numactl \
    xz-utils \
    bsdmainutils \
    git \
    man-db \
    imagemagick \
    libexpat1-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libgdbm-dev \
    libyaz-dev \
    libwrap0-dev \
    zlib1g-dev \
    binutils \
    pwgen \
    curl \
    telnet

# Prepare to install
# OS
RUN apt clean \
    && apt update \
    && apt upgrade -y \
    && apt dist-upgrade -y \
    && apt install --assume-yes --no-install-recommends ${PRE_BUILD} ${REQ_BUILD}
# Perl
RUN apt install --assume-yes --no-install-recommends perl-doc \
    cpanminus \
    libcapture-tiny-perl \
    libdbd-mysql-perl \
    libmodule-install-perl \
    libyaml-perl \
    libb-utils-perl \
    carton
# Workers' Manager
RUN apt install --assume-yes --no-install-recommends gearman \
    gearman-server \
    gearman-tools \
    libgearman-dev
# MySQL
RUN apt install --assume-yes --no-install-recommends mysql-client \
    libmysqlclient-dev

# NodeJS
RUN curl -sL ${NODEJS_URL} > /tmp/nodejs_preinstall \
    && sed -i 's/apt\-get/apt/g' /tmp/nodejs_preinstall \
    && sed -i 's/apt\ install\ -y/apt\ install\ \-\-assume\-yes\ \-\-no\-install\-recommends/g' /tmp/nodejs_preinstall \
    && chmod +x /tmp/nodejs_preinstall \
    && bash - /tmp/nodejs_preinstall \
    && apt install --assume-yes --no-install-recommends nodejs \
    && rm /tmp/nodejs_preinstall

# Clone LibreCat
RUN mkdir -p ${LIBRECATHOME} \
     && git clone https://github.com/LibreCat/LibreCat.git ${LIBRECATHOME}

#   Installing Perl-Modules and compiling everything
#   Finalizing setup and run Web-Interface under :5001
#
# Building LibreCat
WORKDIR ${LIBRECATHOME}
# Goettingen specific: start ########
RUN git checkout ${LIBRECAT_VERSION}
# Goettingen specific: end ########
RUN sed -i 's/==/\>=/g' cpanfile 
RUN echo "requires 'Devel::Camelcadedb';" >> cpanfile

RUN carton install
RUN chmod +x bin/generate_forms.pl \
    && perl bin/generate_forms.pl

#Install perl debug module: https://github.com/Camelcade/Perl5-IDEA/wiki
#The module is now also added to the cpan file to place the dependency into the local directory by carton
RUN cpanm install Devel::Camelcadedb

# 
# Finalizing the LibreCat Image with SUB Layer
#
# Local Layer
RUN git clone https://github.com/subugoe/goefis.git ${LOCAL_LAYER}
WORKDIR ${LOCAL_LAYER}
RUN npm install \
    && npm run build-css prefix-css

RUN mkdir -p ${SETTINGS_LAYER}
COPY settings ${SETTINGS_LAYER}

# Configurations
WORKDIR ${LIBRECATHOME}
RUN mkdir logs
COPY layers.yml .
COPY boot.sh .
COPY gearman-entrypoint.sh .
COPY docker-entrypoint.sh .

RUN chown -R librecat:librecat ${LIBRECATHOME} ${LOCAL_LAYER} ${SETTINGS_LAYER}

# Clean up
RUN apt purge -y ${PRE_BUILD} \
    && apt --purge autoremove -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

USER librecat:librecat

VOLUME ["/usr/share/elasticsearch/data","/var/lib/mysql", "/srv/LibreCat/logs"]

EXPOSE 3306 4730 5001 9200 9300

ENTRYPOINT ["./docker-entrypoint.sh"]
