FROM ubuntu:14.04
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
# creating a predecessor for the LibreCat Image
#

# Add extra Repository for ElasticSearch
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 \
    && echo "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" > /etc/apt/sources.list.d/elasticsearch-1.7.list
RUN sed -i '/multiverse/s/#[\ ]*deb/deb/g' /etc/apt/sources.list
RUN groupadd -g 5000 librecat \
    && useradd -g 5000 -u 5000 -d /srv/LibreCat -s /bin/bash -c "LibreCat User" librecat

ENV LIBRECATHOME /srv/LibreCat
ENV MYSQL_USER root
ENV NOTVISIBLE "in users profile"

# Prepare to install
RUN apt-get clean \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get dist-upgrade -y

RUN apt install -y build-essential
RUN apt install -y ca-certificates \
    wget \
    g++ \
    numactl \
    xz-utils \
    bsdmainutils \
    git \
    man-db \
    ImageMagick \
    libexpat1-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libgdbm-dev \
    libyaz-dev \
    libwrap0-dev \
    zlib1g \
    zlib1g-dev \
    binutils \
    pwgen \
    libaio1 \
    curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - \
    && apt install -y nodejs
RUN apt install -y perl-doc \
    cpanminus \
    libcapture-tiny-perl \
    libdbd-mysql-perl \
    libmodule-install-perl \
    libyaml-perl \
    libb-utils-perl \
    carton
RUN apt install -y gearman \
    gearman-server \
    gearman-tools \
    libgearman-dev
RUN apt install -y mysql-client \
    libmysqlclient-dev

RUN sed -i '/socket/ d' /etc/mysql/my.cnf \
    && sed -i '/\[mysqld\]/a bind-address\ =\ 0.0.0.0' /etc/mysql/my.cnf

# git clone LibreCat
RUN cd /srv \
     && git clone --recursive https://github.com/subugoe/LibreCat.git \
     && cd LibreCat \
     && git fetch \
     && git checkout dev

WORKDIR $LIBRECATHOME
#   Installing Perl-Modules and compiling everything
#   Finalizing setup and run Web-Interface under :5001
#
ENV LANG en_US.UTF-8
ENV LANGUAGE en.UTF-8
ENV LC_COLLATE en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_PAPER en_US.UTF-8
ENV LC_ADDRESS en_US.UTF-8
ENV LC_MONETARY en_US.UTF-8
ENV LC_NUMERIC en_US.UTF-8
ENV LC_TELEPHONE en_US.UTF-8
ENV LC_IDENTIFICATION en_US.UTF-8
ENV LC_MEASUREMENT en_US.UTF-8
ENV LC_TIME en_US.UTF-8
ENV LC_NAME en_US.UTF-8
RUN locale-gen en_US.UTF-8

# Building LibreCat
RUN sed -i 's/==/\>=/g' cpanfile \
    && sed -i '/CrossRef/ d' cpanfile
RUN cpanm -nq --installdeps --skip-installed Catmandu
RUN cpanm -nq --installdeps --skip-installed Catmandu::MARC
RUN cpanm -nq --installdeps --skip-installed Catmandu::Solr
RUN cpanm -nq --installdeps --skip-installed Catmandu::Store::Solr
RUN cpanm -nq --installdeps --skip-installed Catmandu::Importer::OAI
RUN cpanm -nq --installdeps --skip-installed Catmandu::Importer::Solr
RUN cpanm -nq --installdeps --skip-installed .
RUN cpanm -nq --installdeps --skip-installed Gearman::XS::Worker
RUN carton install
RUN chmod +x bin/generate_forms.pl \
    && perl bin/generate_forms.pl
# Building the FrontEnd
RUN npm install

# Configuration files
COPY conf/log4perl.conf .
COPY conf/catmandu.local.yml .
COPY conf/catmandu.store.yml .
# Services and Settings
COPY gearman-entrypoint.sh ./gearboot.sh
COPY conf/mysql-init.sql .
COPY docker-entrypoint.sh .

RUN chown -R librecat:librecat /srv/LibreCat

# Install & configure SSH
RUN mkdir /var/run/sshd \
    && apt install -y openssh-server \
    && sed -i 's/PermitRootLogin without-password/PermitRootLogin no/' /etc/ssh/sshd_config \
    && sed -i '/Port/ s/22/2022/g' /etc/ssh/sshd_config
# SSH login fix. Otherwise user is kicked off after login
# For Use in Production, change the Password 'librecat:<New_Password>'
RUN sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd \
    && sed -i '/\%sudo/ s/$/\nlibrecat  ALL=(ALL) NOPASSWD:ALL/' /etc/sudoers \
    && sed -i '/requiretty/ d' /etc/sudoers \
    && echo "export VISIBLE=now" >> /etc/profile \
    && echo 'librecat:Top$3cr3T' | chpasswd

VOLUME ["/usr/share/elasticsearch/data","/srv/LibreCat/logs"]

EXPOSE 2022 3306 4730 5001 9200 9300

CMD ["./docker-entrypoint.sh"]
