FROM ubuntu:16.04
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
#   Step 1: Adding different repostories and install different tools i.e. build-essentials and so on
#

# Adding 'multiverse' in order to be able to install OpenJDK later
RUN sed -i '/multiverse/s/#[\ ]*deb/deb/g' /etc/apt/sources.list

# Prerequisites
RUN set -x \
    && apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        wget \
        numactl \
        bzip2 \
        unzip \
        xz-utils \
        curl \
        sudo \
        cpanminus \
        build-essential \
        libexpat1-dev \
        libssl-dev \
        libxml2-dev \
        libxslt1-dev \
        libgdbm-dev \
        libcapture-tiny-perl \
        vim \
        bsdmainutils \
        tree \
        man-db \
        perl-doc \
        git \
        libdbd-mysql-perl \
    && rm -rf /var/lib/apt/lists/*

# MongoDB
RUN set -ex \
    apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys DFFA3DCF326E302C4787673A01C4E7FAAAB2461C \
    && apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 42F3E95A2C4F08279C4960ADD68FA50FEA312927
# ElasticSearch
RUN wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -
