FROM librecat_gosu:devel
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
#   Step 3: Installing Java JRE-8
#

# Environment Variables
ENV LANG C.UTF-8
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV JAVA_VERSION 8u91
ENV JAVA_DEBIAN_VERSION 8u91-b14-0ubuntu4~16.04.1
ENV CA_CERTIFICATES_JAVA_VERSION 20160321

# Installing Java JRE-8
RUN set -x \
    && apt-get update \
    && apt-get install -y \
        openjdk-8-jre-headless="$JAVA_DEBIAN_VERSION" \
        ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION" \
    && rm -rf /var/lib/apt/lists/*

# see CA_CERTIFICATES_JAVA_VERSION notes above
RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure
