FROM librecat_github:devel
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
#   Step 7: Finally compiling LibreCat and starting the Service
#

WORKDIR /srv/LibreCat
RUN cpanm --notest --installdeps .

RUN perl bin/generate_forms.pl

ENTRYPOINT ["starman","bin/app.pl"]
