FROM librecat_base:devel
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
#   Step 2: Installing GoSu 
#

# Environment Variables
ENV LANG C.UTF-8
ENV GOSU_VERSION 1.7

# Installing GoSu
RUN set -x
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true
    && rm -rf /var/lib/apt/lists/*
