FROM librecat_jre:devel
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
#   Step 4: Installing ElasticSearch 1.7
#

# Environment Variables
ENV ELASTICSEARCH_MAJOR 1.7
ENV ELASTICSEARCH_VERSION 1.7.5
ENV ELASTICSEARCH_REPO_BASE http://packages.elasticsearch.org/elasticsearch/1.7/debian
ENV PATH /usr/share/elasticsearch/bin:$PATH

RUN echo "deb $ELASTICSEARCH_REPO_BASE stable main" > /etc/apt/sources.list.d/elasticsearch-$ELASTICSEARCH_MAJOR.list
# Installing ElasticSearch
RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends elasticsearch=$ELASTICSEARCH_VERSION \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/share/elasticsearch

RUN set -ex \
    && for path in \
        ./data \
        ./logs \
        ./config \
        ./config/scripts \
    ; do \
        mkdir -p "$path"; \
        chown -R elasticsearch:elasticsearch "$path"; \
done

VOLUME /usr/share/elasticsearch/data

COPY config ./config
COPY docker-entrypoint.sh /elasticsearch-startup.sh

EXPOSE 9200 9300
ENTRYPOINT ["/elasticsearch-startup.sh"]
CMD ["elasticsearch"]
