# Dockerizing LibreCat

FROM ubuntu:16.04
MAINTAINER Arash Samadi (asamadi@sub.uni-goettingen.de)

RUN apt-get update && apt-get install -y \
  sudo \
  cpanminus \
  build-essential \
  libexpat1-dev \
  libssl-dev \
  libxml2-dev \
  libxslt1-dev \
  libgdbm-dev \
  libcapture-tiny-perl\
  curl \
  wget \
  vim \
  bsdmainutils \
  tree \
  man-db \
  perl-doc \
  git \
  libdbd-mysql-perl
