# Dockerizing LibreCat
FROM centos:6.7
MAINTAINER Arash Samadi (asamadi@sub.uni-goettingen.de)

RUN sed -i 's/enable=0/enable=1/g' /etc/yum.repos.d/CentOS-Base.repo
RUN yum update -y
# Prapre 
RUN yum groupinstall "Development Tools" -y \
    && yum install -y perl-ExtUtils-MakeMaker \
    perl-CPAN \
    tcp_wrappers-devel \
    perl-YAML \
    perl-Module-Build \
    expat-devel \
    expat \
    openssl-devel \
    openssl \
    libxml2 \
    libxml2-devel \
    libxslt \
    libxslt-devel \
    gdbm \
    gdbm-devel \
    ImageMagick

# Upgrade Perl Version (http://www.theshell.guru/install-latest-perl-5-18-centos-6-4/)
WORKDIR /tmp
RUN wget http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/perl-5.18.2.tar.bz2 \
    && tar xfvj perl-5.18.2.tar.bz2 \
    && cd perl-5.18.2 \
    && ./Configure -des \
    && make \
    && make install
    && ln -sf /usr/local/bin/perl /usr/bin/perl

RUN source ~/.profile
