FROM librecat_pre
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
#   Step 7: Finally compiling LibreCat and starting the Service
#
#WORKDIR /usr/local/bin
#RUN curl -L http://cpanmin.us -o cpanm \
#    && chmod +x cpanm
#RUN wget http://www.cpan.org/authors/id/D/DS/DSCHOEN/Gearman-XS-0.12.tar.gz \
#    && tar xfvz Gearman-XS-0.12.tar.gz \
#    && cd Gearman-XS-0.12 \
#    && perl Makefile.PL \
#    && make && make install
#WORKDIR /srv/LibreCat
#COPY services.sh .
#RUN ./services.sh

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_COLLATE C
ENV LC_CTYPE en_US.UTF-8
ENV LIBRECATHOME /srv/LibreCat
ENV PERLHOME /usr/local/bin
ENV PERL_LOCAL_LIB_ROOT "/usr/local/lib"
#ENV PERL_MB_OPT "--install_base /root/perl5"
#ENV PERL_MM_OPT "INSTALL_BASE /root/perl5"
#ENV PERL5LIB "/usr/local/lib:$LIBRECATHOME/lib:$LIBRECATHOME/local/lib/perl5:$PERL_LOCAL_LIB_ROOT:$PERL5LIB"
ENV PATH "/root/perl5/bin:$LIBRECATHOME/bin:$PERLHOME:$PATH"
ENV PERL_MM_USE_DEFAULT 1

#RUN mkdir -p /root/.cpan/buil /root/.cpan/sources /root/perl5
RUN yes | cpan CPAN
#RUN yes | cpan App::cpanminus

RUN cpanm -n -q --installdeps Test::More
#RUN cpanm --notest --installdeps Module::Build
#RUN cpanm --notest --installdeps Module::Install
#RUN cpanm --notest --installdeps YAML
RUN cpanm --notest --installdeps Catmandu
#RUN cpanm --notest --installdeps --verbose Gearman::XS

#RUN cpanm --notest --installdeps Catmandu::MARC
#RUN cpanm --notest --installdeps .
#RUN cpanm Carton
#RUN carton install

#COPY .my.cnf ~/
#RUN mysql < devel/mysql.sql \
#    && mysql librecat_system < devel/librecat_system.sql \
#    && mysql librecat_backup < devel/librecat_backup.sql \
#    && mysql librecat_metrics < devel/librecat_metrics.sql \

#RUN chmod +x bin/generate_forms.pl \
#   && bin/generate_forms.pl \
#    && ./index.sh drop \
#    && ./index.sh create

#EXPOSE 9200 9300 3306 5001

#COPY catmandu.local.yml .
#COPY catmandu.store.yml .

#ENTRYPOINT ["./boot.sh"]
