FROM librecat_gosu
MAINTAINER  Arash Samadi (samadi@sub.uni-goettingen.de)
# 
#   Step 3: Installing Java JRE-8
#

# Environment Variables
ENV LANG C.UTF-8
ENV JAVA_HOME /usr/lib/jvm/jre-1.7.0-openjdk
RUN source /etc/bashrc

# Installing Java JRE-8
RUN set -x \
    && yum update -y \
    && yum install -y java-1.7.0-openjdk \
    && yum clean all
